### PR TITLE
[WIP] Multisite Support

### PR DESCRIPTION
**Pull request by AntJanus**
Ref: #111 

Todo:

* [ ] fix whitespace
* [ ] add multisite declaration to wp-config
* [ ] test it out!

### CODE REVIEW

**Comment by zanematthew** [comment]
Whats the latest on this?

**Comment by ericclemmons** [comment]
@zanematthew Whoops, @AntJanus doesn't work on this project anymore.  It just needs someone to pick back up on it...

**Comment by zanematthew** [comment]
@ericclemmons Thanks for the comment and the 411, worth knowing...(making mental note to add another repo to my bucket list of projects to contribut to).

**Comment by EvanK** [comment]
Closing this out for now

**Pull request closed without merging**
